name: Test Action

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '1 2 5 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  first-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run the action
      uses: ./
      with:
        packages: latex-bin
        cache_version: ${{ github.run_id }}_${{ github.run_attempt }}
    - run: pdflatex test.tex

  run-with-cache:
    needs: first-run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run the action
      uses: ./
      with:
        packages: latex-bin
        cache_version: ${{ github.run_id }}_${{ github.run_attempt }}
        repository: https://127.0.0.42/not-a-texlive-mirror/
    - run: pdflatex test.tex

  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
